
service: storage

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8


functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
  
  signup:
    handler: signUp.signup

  presignup:
    handler: preSignUp.presignup
    events:
      - cognitoUserPool:
          pool: pictures-user-pool
          trigger: PreSignUp
          
    

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        # Generate a name based on the stage
        UserPoolName: pictures-user-pool
        # Set email as an alias
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
            TemporaryPasswordValidityDays: 7


    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        # Generate an app client name based on the stage
        ClientName: pictures-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: true
